ALTER TABLE "Quotation" ADD COLUMN IF NOT EXISTS "preGstAmount" DECIMAL(65,30) DEFAULT 0;
ALTER TABLE "Quotation" ADD COLUMN IF NOT EXISTS "igst" DECIMAL(65,30) DEFAULT 0;
ALTER TABLE "Quotation" ADD COLUMN IF NOT EXISTS "discountPercent" DECIMAL(65,30) DEFAULT 0;
ALTER TABLE "QuotationItem" ADD COLUMN IF NOT EXISTS "serialNumber" INTEGER;
ALTER TABLE "QuotationItem" ADD COLUMN IF NOT EXISTS "hsnSacCode" TEXT;
ALTER TABLE "QuotationItem" ADD COLUMN IF NOT EXISTS "amount" DECIMAL(65,30);
